<?php

/**
 * @file
 * Provides a cities migration entity entity type.
 */

use Drupal\Core\Render\Element;
use Drupal\cities_migration_entity\Entity\CitiesMigrationEntity;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function cities_migration_entity_theme() {
  return [
    'cities_migration_entity' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for cities migration entity templates.
 *
 * Default template: cities-migration-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the cities migration entity information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_cities_migration_entity(array &$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 */
function cities_migration_entity_user_cancel($edit, UserInterface $account, $method) {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish cities migration entities.
      $storage = \Drupal::entityTypeManager()->getStorage('cities_migration_entity');
      $cities_migration_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->execute();
      foreach ($storage->loadMultiple($cities_migration_entity_ids) as $cities_migration_entity) {
        $cities_migration_entity->set('status', FALSE);
        $cities_migration_entity->save();
      }
      break;

    case 'user_cancel_reassign':
      // Anonymize cities migration entities.
      $storage = \Drupal::entityTypeManager()->getStorage('cities_migration_entity');
      $cities_migration_entity_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->execute();
      foreach ($storage->loadMultiple($cities_migration_entity_ids) as $cities_migration_entity) {
        $cities_migration_entity->setOwnerId(0);
        $cities_migration_entity->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function cities_migration_entity_user_predelete(UserInterface $account) {
  // Delete cities migration entities.
  $storage = \Drupal::entityTypeManager()->getStorage('cities_migration_entity');
  $cities_migration_entity_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->execute();
  $cities_migration_entities = $storage->loadMultiple($cities_migration_entity_ids);
  $storage->delete($cities_migration_entities);
}
